### ISSUE TITLE
Interested in Contributing to this project

### ISSUE THREAD

**Issue by adarshmadrecha** [dhananjay1405/tally-database-loader#1]
@dhananjay1405, at Madrecha Solutions we have a team of 6 developers. We as a team would love to contribute to this project. If you have any roadmap for this project, please do share.
Can reach me at `adarsh@madrecha.com`

**Comment by dhananjay1405** [comment]
@adarshmadrecha yes sure
Roadmap of the project (or say some goals which it is intended to achieve) are as below:

1) To keep it a pure data extraction and bulk loading utility targeting popular RDBMS
2) GUI-less command-line utility, intended to be executed by Front-end programs of C#, Java, Python, etc via shell command execution
3) Step-by-Step addition of more Tables and Fields of Tally into Database
4) Introducing compatibility even for No-SQL JSON database like MongoDB, Azure Cosmos DB, etc, which are available on Free-tier, for small business units, who have very less data & cannot afford VPS or popular Cloud platform with costly RDBMS

This is the very first draft of project, which has been tested on simple Tally data with lowest complexity. But, I will require a team effort in testing this project, so that I can focus on adding many more tables / fields of Tally. Testing is the most crucial activity in this project & it needs to be done on variety of Tally data, to catch bugs early (as Tally abruptly crashes if anything goes wrong in XML TDL)

So, I will appreciate if you could contribute toward this crucial activity of testing which is need on hour currently. We will discuss further, once this project achieves stability
