### ISSUE TITLE
Cannot Import data in MySQL Version 8 

### ISSUE THREAD

**Issue by Sagar-R-Parmar** [dhananjay1405/tally-database-loader#10]
Hi @dhananjay1405  I am using Tally Prime and MySQL version 8 and all dependencies installed but getting following error.

Error from database.executeMysql() at 
Invalid MySQL username/password/Authentication
--------------------------------------------------------------------------------

**Comment by Sagar-R-Parmar** [comment]
Hi @dhananjay1405 a quick update for the same issue your code works fine using the old MySQL 5.x legacy authentication method on MySQL 8. 
To use your code on MySQL 8, server needs to be reconfigured (not reinstalled) to use legacy authentication method instead of recommended strong password encryption for authentication using SHA256-based password.
![Screenshot 2021-12-11 153131](https://user-images.githubusercontent.com/81258051/145672587-3f11b32f-f282-4988-82bf-05600c8df65b.png)
 
I hope you will update your code to work with MySQL 8 with recommended strong password encryption method. Till then above mentioned workaround is fine.

**Comment by dhananjay1405** [comment]
Ya I know this issue & had already updated this on GitHub FAQ page few months ago (you will find screenshot)
Actually for MySQL I depend on Node.JS 3rd party package & probably its author was not able to implement caching_sha2 authentication. Currently I am working on ramping-up the security via SSL tunnel of data exchange, so that not only password but complete data is encrypted end-to-end. SSL handshake is already implemented for SQL Server & PostgreSQL. For MySQL, it is a bit manual (like you need to generate keys using openssl manually). Will definitely come out with some robust solution for this.

PostgreSQL seems to be a promising candidate when it comes to security. I am waiting for that day when Google Sheet JDBC supports postgresql.
