### ISSUE TITLE
Import database taking too long

### ISSUE THREAD

**Issue by worldfellow** [dhananjay1405/tally-database-loader#15]
Hi ,

I have a database which is 509 mb in size it is taking a lot of time to import is there are connection timeout , how do i know how much data is imported and how much is pending

**Comment by dhananjay1405** [comment]
No, as such connection timeout does not occurs. I have similar Tally data of 400 MB Tally data, where Tally takes 9 GB of RAM & around 12 min to generate this data. Ensure you have sufficient RAM in your PC like 16 GB or more is recommended. There is no way to know how much is pending, since it is HTTP Request to Tally. Tally does not notify how much data is pending. As of now, try splitting company if possible.

I am working on a feature of incremental sync, wherein for subsequent sync, only data that was added/modified/deleted will be sync.

**Comment by dhananjay1405** [comment]
@worldfellow 
Incremental sync is now available. This shall resolve your issue.
First time full sync is required, after that you can shift to incremental sync. Kindly check-out the documentation.
