### ISSUE TITLE
Support for MongoDB

### ISSUE THREAD

**Issue by jbeuria** [dhananjay1405/tally-database-loader#17]
Hello Dhananjay, 

This is a very nice open source contribution. Hats off!  Can this be configured for MongoDB?

Best 
JB

**Comment by dhananjay1405** [comment]
Yes, I have plans to add support to majority of NoSQL database platform like
1. MongoDB
2. Cosmos DB
Initially to kick-off, I will be adding an option to export data in JSON format (just like I gave CSV option). This opens up path to upload this JSON to any of NoSQL database platform of user's choice (like even GCP & AWS)

@jbeuria  Thanks for reminding this. I am converting this thread to **feature request** .

**Comment by jbeuria** [comment]
@dhananjay1405 thanks! looking forward to a new release.

**Comment by dhananjay1405** [comment]
@jbeuria just to update you, project now supports exporting of JSON files. In technology simple specify **json** instead of mssql, which will generate JSON files. I am not aware how to load JSON files into MongoDB (maybe you need some Python coding for this). But I am sure this option can serve as enabler (or starting point) for your requirement.
