### ISSUE TITLE
Connection-error Azure data studio

### ISSUE THREAD

**Issue by rupeshbh123** [dhananjay1405/tally-database-loader#26]
How to resolve the Connection-error Azure data studio kindly help me.
I attached screen shot of error for your reference
![Screenshot](https://github.com/dhananjay1405/tally-database-loader/assets/157875161/970dfb1b-aec7-4bb4-8334-d561cb1aad4a)

**Comment by dhananjay1405** [comment]
@rupeshbh123 This error comes when you attempt to connect to locally running SQL Server, where SSL is not present. SSL is required only for cloud facing SQL Server. You need to click Enable Trust server certificate button.

**Comment by dhananjay1405** [comment]
@jiten-biz some updates as of present since this is very old thread

- Microsoft has officially stopped developing and maintaining Azure Data Studio. Kindly use SQL Server Management Studio, where you will not face this issue.
- If you are using SQL Server 2022 or higher, then you need to enable trust server certificate option by tweaking connection settings in SQL Server Management Studio (you can google it and you should find screenshots for troubleshooting)
