### ISSUE TITLE
Request for Guidance: Merging Data from Two Companies in PostgreSQL

### ISSUE THREAD

**Issue by Atharva-H** [dhananjay1405/tally-database-loader#27]
Issue: My company typically splits data after each financial year to manage the large dataset efficiently. Currently, we have two separate companies, eg. ABCCompany(22-23) and ABCCompany(23-24), each with its distinct dataset.

I am exploring the possibility of merging the data from both companies into a single PostgreSQL database (version 15.4) on AWS RDS. I use TallyPrime 4.0 on Windows server OS.

Thank you.

**Comment by dhananjay1405** [comment]
@Atharva-H  proposed solution which you can try:
You will require help of ETL tool for this. I will propose, make use of AWS Glue if you are already leveraging AWS platform. I am not much into ETL stuff, but still aware of the capabilities.

Create 3 databases by names something like this as mentioned below using the same table structure found in **database.sql** file:
1. tally_2223 (for FY 2022-23)
2. tally_2324 (for FY 2023-24)
3. tally_merged (combined database)

Run sync for FY 2022-23 after you split the company in Tally into database **tally_2223** . Assuming that you will never modify this company data again in future (as you have split & freeze it), you would never require sync again for this. This database will stay static.

Schedule daily sync for FY 2023-24 into the database **tally_2324** on specific time every day. I use Windows Task Schedular for this.

You will have to create AWS Glue job / pipeline, which would implement below logic:
1) Job will first truncate all the tables of database **tally_merged**
2) Then it should copy all the rows table-by-table from database **tally_2223** into **tally_merged** (in short replicate entire database)
3) Next job should copy specific rows from all the master tables i.e. tables with prefix mst_* from **database tally_2324** which do not exist in **tally_merged** table-by-table, treating **guid** field as primary key to check for duplicate.
4) Next job will copy all the transaction tables i.e. tables with prefix trn_* from **tally_2324** into **tally_merged** database again table-by-table (no not worry for duplicate this time, as transactions 2 different year never overlap)

You need to establish some trigger to run this pipeline, which can be tricky. Generally, I automate Tally to Database sync using Windows Task Schedular at specific time of day. So, if you follow the same strategy, safely after 25-30min from sync time (assuming sync will finish in that duration), you can schedule a trigger to run this pipeline.

If you are not ETL fan, you can go for Python jobs for the above logic, it is your choice, which thing you are comfortable with.

Some push-back you should expect with this approach:

- Re-naming of ledgers / groups / stock items / ... all the master type of objects of Tally in future financial year, will lead to database integrity issues.
- Your pipeline should never run when sync is going on, otherwise it will create mess
