### ISSUE TITLE
Issue in Godown Parent GUID

### ISSUE THREAD

**Issue by JEEVAN28** [dhananjay1405/tally-database-loader#29]
Hello,

I noticed that in mst_godown table _parent guid is not captured and reason is due to bug in yaml file

**field: if $$IsEmpty:$Address then "" else $Guid:Godown:$Parent**

basically condition should be like below
**field: if $$IsEqual:$Parent:$$SysName:Primary then "" else $Guid:Godown:$Parent**

Jeevan Pendhari

**Comment by dhananjay1405** [comment]
@JEEVAN28 a good catch, I never realized this bug since I played with a very simple data when it came to godown.
It is good to see that you have really understood the mechanism of YAML file & how it is driving data extraction from Tally.
The next push of the code changes I make, I am going to include this fix to the YAML file, to close this bug.

Looking forward for more bug hunting from your end, as this activity is really important for open-source projects.
