### ISSUE TITLE
Database Insert Error

### ISSUE THREAD

**Issue by sau6402** [dhananjay1405/tally-database-loader#3]
Hi @dhananjay1405 ,

I tried running the script but I am getting the following error.
![image](https://user-images.githubusercontent.com/762849/112941539-5edcc200-914c-11eb-91ff-689beefc2736.png)

The mst_group table has 7 columns but the insert statement in the error-log is having only 4, which is causing the issue.
PFA screenshot fo mst_group table showing 7 columns.
![image](https://user-images.githubusercontent.com/762849/112941789-c8f56700-914c-11eb-9c93-15ddbbabdf14.png)

Let me know what we can do here.

--
Regards
Saurabha Joglekar

**Comment by dhananjay1405** [comment]
I can clearly see all textual fields like Name, Parent, Primary Group being skipped. I had observed the same issue 6-7 months ago, in Power Query project for Excel, as XML files are common for both of these projects. Let me brief you why this error comes. Tally enclosed each and every field in double quotes (which is perfect). But it fails to escape double quotes inside string type of data (via 2 consecutive double quotes, as specified in CSV format specification), thereby raising exception while import. So to fix this bug of Tally, I used a TDL function called **StringFindAndReplace** to replace single instance of double quote with 2 consecutive double quotes. This TDL function is not supported by older versions of Tally, which is causing this issue.

**Safe & Permanent Resolution:**
Update your Tally.ERP 9 to latest version of 6.6.3, or even better migrate to Tally Prime, which is already updated

**Unsafe & Temporary Fix:**
Remove this **StringFindAndReplace** TDL function in _all XML for all String type of fields_, like shown below

Before replacement:
```xml
<FIELD NAME="FldName">
    <SET>$$StringFindAndReplace:$Name:'"':'""'</SET>
</FIELD>
```

After replacement:
```xml
<FIELD NAME="FldName">
    <SET>$Name</SET>
</FIELD>
```

This should temporarily solve your problem of blank output of data for String type of fields in CSV files, on which database loading depends. But again be cautious, this temporary fix is bound to fail when double quotes is found in textual data. I will personally recommend to go for **resolution** instead of **fix**
